version: "3.7"
services:
  app:
    build: .
    volumes:
      - .:/app:cached
      - home:/home/app
    env_file: app.env
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis:alpine
volumes:
  home:
