version: "3.7"
services:
  embulk:
    build: .
    volumes:
      - .:/app:cached
      - home:/home/app
    environment:
      REDIS_URL: redis://redis:6379
    env_file:
      - embulk.env
    depends_on:
      - redis
  redis:
    image: redis:alpine
volumes:
  home:
